import React from 'react'
import { useState,useEffect } from 'react'
import {Loader , Card, FormFields} from '../Components';


const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className="mt-5 font-bold uppercase text-xl text-[#6449ff]">
      {title}
    </h2>
  );
};


const Home = () => {

    const [loading, setloading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText , setSearchText] =useState('');
    const [searchResults, setSearchResults] = useState(null);
    const [searchTimeouts, setSearchTimeouts] = useState(null);
    useEffect(()=>{
      const fetchPosts = async()=>{
        try {
          setloading(true);
          const response = await fetch('http://localhost:8080/api/v1/posts',{
            method : 'GET',
            headers : {
              'Content-Type' : 'application/json',
            },
          });
          if(response.ok) {
            const result = await response.json();
            setAllPosts(result.data.reverse());
          }
        
          
        } catch (error) {
          alert(error);
        }finally{
          setloading(false);
        }
      }
      fetchPosts();
    },[]);


    const handleSearchChange = (e) => {
      clearTimeout(searchTimeouts);
      setSearchText(e.target.value);
    
      setSearchTimeouts(
        setTimeout(() => {
          const searchResult = allPosts.filter((item) => 
            item.name.toLowerCase().includes(searchText.toLowerCase()) || 
            item.prompt.toLowerCase().includes(searchText.toLowerCase())
          );
          setSearchResults(searchResult);
        }, 500)
      );
    };
    

  return (
   <section className='mx-auto max-w-7xl'>
    <div>
      <h1 className='font-extrabold text-[32px] text-[#222328]'>
        The Community Showcase.
      </h1>
      <p className='mt-2 text-[#666e75] text-[16px] mx-w-[500px] '>
        Browse Through a Collection of Imaginative and Visually Stunning images generated by ImageAI. 
      </p>
    </div>

    <div className='mt-16'>
      <FormFields
        labelName="search post"
        type="text"
        name="text"
        placeholder="search by name or prompt"
        value={searchText}

        handleChange={handleSearchChange}
      />
    </div>

    <div className='mt-10'>
      {
        loading ? ( <div className=' flex justify-center items-center'> 
          <Loader/>
        </div> 
          ):
          (<>
            {searchText && (
              <h2 className='text-[#666e75] font-medium text-xl mb-3'>
                showing Results for <span className='text-[#222328] '> {searchText}</span>
              </h2>
            )}

            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                {
                  searchText ? (
                    <RenderCards 
                      data={searchResults}
                      title = "no result Found"
                    />
                  ):
                  ( 
                    <RenderCards 
                      data={allPosts}
                      title = "no posts Found"
                    />
                  )
                }
            </div>
          </>)
      }

    </div>

   </section>
  )
}

export default Home