import React from 'react'
import { getRandomPrompt } from '../utils';
import {useNavigate } from 'react-router-dom'
import { preview } from '../assets';
import {FormFields , Loader} from '../Components';
import { useState } from 'react';

export const Post = () => {

  const navigate = useNavigate();
  const [form , setForm] = useState({
    name : '',
    prompt : '',
    photo : '',
  });

  const [generateImg, setGenerateImg] = useState(false);
  const [loading, setLoading] = useState(false);


  const generateImage =  async()=>{

    if(form.prompt){
      try {
        setGenerateImg(true);
        const response = await fetch('https://imageai-backend.onrender.com/api/v1/imageAI',{
          method : 'POST',
          headers : {
            'Content-Type' : 'application/json',
          },
          body : JSON.stringify({prompt : form.prompt})
        })

        const data = await response.json();

        setForm({...form, photo : `data:image/jpeg;base64,${data.photo}`});
      
      } catch (error) {
        alert(error);
      }finally{
        setGenerateImg(false); 
      }
    }else{
      alert('Please Enter Prompt');
    }
  }
  const handleSubmit = async (e)=>{
    e.preventDefault();
    if(form.prompt && form.photo){

      try {
        setLoading(true);
        const response = await fetch('https://imageai-backend.onrender.com/api/v1/posts',{
          method : 'POST',
          headers : {
            'Content-Type' : 'application/json',
          },
          body : JSON.stringify(form)
        });

        await response.json();
        navigate('/');
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
      
    }else{
      alert('Please fill all the fields');
    }
  }
  const handleChange = (e)=>{ 

    setForm({...form, [e.target.name] : e.target.value });
  };

  const handleSupriseMe = ()=>{
    const randomPrompt = getRandomPrompt(form.prompt);
    setForm({...form, prompt : randomPrompt});
  }


  return (
    <section className='max-w-7xl mx-auto'>
      <div>
      <h1 className='font-extrabold text-[32px] text-[#222328]'>
        Create.
      </h1>
      <p className='mt-2 text-[#666e75] text-[16px] mx-w-[500px] '>
        Create a Collection of Imaginative and Visually Stunning images generated by ImageAI and Share with Community. 
      </p>
    </div>

    <form onSubmit={handleSubmit} className='mt-16 max-w-3xl'> 
      <div className='flex flex-col gap-5'>
          <FormFields 
            labelName='Your Name'
            type='text'
            name='name'
            placeholder='Narendra'
            value={form.name}
            handleChange = {handleChange} 
          />
          <FormFields 
            labelName='Prompt'
            type='text'
            name='prompt'
            placeholder='a painting of a fox in the style of Starry Night'
            value={form.prompt}
            handleChange = {handleChange} 
            isSupriseMe
            handleSupriseMe = {handleSupriseMe}
          />

          <div className='relative bg-gray-50 border border-gray-300 rounder-lg text-gray-900 text-sm focus:ring-[#4649ff] focus:border-[#4649ff]  p-3 h-64 w-64 flex justify-center items-center  '>
              {
                form.photo ? ( 
                  <img src={form.photo}
                  alt={form.promt}
                  className='w-full h-full object-contain'
                  />
                ):(
                  <img src={preview} alt='preview' className='w-9/12 h-9/12 object-contain opacity-40' />
                )
              }
              {generateImg && (
                    <div className='absolute inset-0 z-0 flex  justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg'>
                      <Loader />
                    </div>
                  )}
          </div>    
      </div>

      <div className='mt-5 flex gap-5'>
        <button
          type = 'button'
          onClick={generateImage}
          className='text-white bg-green-500 px-5 py-2.5 text-sm font-medium rounded-md w-full sm:w-auto text-center'
        >
            {generateImg ? 'generating...' : 'Generate'}
        </button>
         
      </div>

      <div className='mt-10'>
        <p  className='mt-2 text-[14px] text-[#666e75] '>
          once you have created your image, you can share it with the community and see what others have created.
        </p>
        <button 
        
        className='text-white bg-[#6469ff] px-5 py-2.5 text-sm font-medium rounded-md w-full sm:w-auto text-center mt-3'>
          {loading ? 'sharing...' : 'Share'}
        </button>

      </div>
    </form>

    </section>
  )
}
